### ISSUE TITLE
Wait - Last Applied Index

### ISSUE THREAD

**Issue by fredfortier** [datafuse-extras/async-raft#3]
I'm starting to use your handy `wait_` test utils.

I see this to wait for logs, suggesting both values should always be equal:
```rust
    #[tracing::instrument(level = "debug", skip(self), fields(msg=msg.to_string().as_str()))]
    pub async fn log(&self, want_log: u64, msg: impl ToString) -> Result<RaftMetrics, WaitError> {
        self.metrics(
            |x| x.last_log_index == want_log,
            &format!("{} .last_log_index -> {}", msg.to_string(), want_log),
        )
        .await?;

        self.metrics(
            |x| x.last_applied == want_log,
            &format!("{} .last_applied -> {}", msg.to_string(), want_log),
        )
        .await
    }
```
This is used after config changes like change membership. But isn't `last_applied` incremented only for `Normal` log entries applied to the state machine?

**Comment by drmingdrmer** [comment]
I think it is here where the `last_applied` is updated:

https://github.com/datafuse-extras/async-raft/blob/53e696872c15b4dbd56316eabae42b962f0197be/async-raft/src/core/client.rs#L334-L339

When a change-memberships log committed, an `Internal` is created here:

https://github.com/datafuse-extras/async-raft/blob/53e696872c15b4dbd56316eabae42b962f0197be/async-raft/src/core/admin.rs#L167

**Comment by fredfortier** [comment]
Got it, thanks! It's a bit confusing to me though because there are two `last_applied` parameters (the state machine and core) with different values (see `MemStore` example below).

```
    async fn apply_entry_to_state_machine(&self, index: &u64, data: &ClientRequest) -> Result<ClientResponse> {
        // Only `EntryPayload::Normal` reaches here
        let mut sm = self.sm.write().await;
        sm.last_applied_log = *index;
        ...
    }
```

In fairness, one is named `last_applied_log` and the other `last_applied` so they are different. But just wanted to flag as a potential naming improvements unless the Raft specs recommends this particular naming.

**Comment by drmingdrmer** [comment]
@fredfortier 
Hm... that's good point!
I think `Statemachine.last_applied_log` is maintained only because `do_log_compaction()` needs this value. 🤔
