### ISSUE TITLE
build fail for stable rust

### ISSUE THREAD

**Issue by simon-fu** [datafuse-extras/async-raft#6]
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /Users/simon/.cargo/git/checkouts/async-raft-c411f5c0ea29c115/ca6ba30/async-raft/src/lib.rs:1:10
  |
1 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `async-raft`

To learn more, run the command again with --verbose.

**Comment by Frederik-Baetens** [comment]
I had this issue for another project, and fixed it by updating to rust 1.55. See if that fixes this for you.

**Comment by drmingdrmer** [comment]
Thank you @Frederik-Baetens
